name: Example e2e tests

on: [push]

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: install dependencies
        run: pnpm install
      - name: Build opaque
        run: pnpm build
      - name: install opaque as dependency
        run: pnpm install
      - name: install Playwright browsers
        run: npx playwright install
      - name: run Playwright tests
        run: cd example-client && pnpm exec playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: example-client/playwright-report/
          retention-days: 30
