name: Example e2e tests

on: [push]

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli
      - name: install wasm-unknown-unknown target
        run: rustup target add wasm32-unknown-unknown
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: install dependencies
        run: pnpm install
      - name: Build opaque
        run: pnpm build
      - name: install Playwright browsers
        run: npx playwright install
      - name: run Playwright tests
        run: cd examples/client-simple-webpack && pnpm exec playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: examples/client-simple/playwright-report/
          retention-days: 30
