name: Tests

on: [push]

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "latest"
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: install dependencies
        run: pnpm install
      - name: Build opaque
        run: pnpm build
      - name: install opaque as dependency
        run: pnpm install
      - name: tests
        run: pnpm test
